#!/bin/bash -x
#
# This simple script builds the the application for Windows
# using a cross compiler.
#

# Build the image
docker build -t qt .

# Now extract the generated binary
#create build directory if it doesnt exist
mkdir -p exe
docker run qt cat release/snake.exe > exe/snake.exe
